name: client build
on:
  push:
    branches:
      - main
      - release
    paths:
      - "client/**"

jobs:
  build-image:
    name: Client image build & Compose & Run on Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/client/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/client/yarn.lock') }}

      - name: Install dependencies
        working-directory: "./client"
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Client build
        working-directory: "./client"
        run: yarn build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kumsil1006
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ghcr.io/kumsil1006/oao:oao-client
          context: ./client

      - name: Copy Docker Compose into the Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ANOTHER_HOST }}
          username: ${{ secrets.ANOTHER_USERNAME }}
          password: ${{ secrets.ANOTHER_PASSWORD }}
          port: ${{ secrets.ANOTHER_PORT }}
          source: "docker-compose.yml"
          target: "oao"

      - name: Run Docker Compose on the Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ANOTHER_HOST }}
          username: ${{ secrets.ANOTHER_USERNAME }}
          password: ${{ secrets.ANOTHER_PASSWORD }}
          port: ${{ secrets.ANOTHER_PORT }}
          script: |
            echo ${{secrets.CONTAINER_REGISTRY_TOKEN}} | docker login ghcr.io -u kumsil1006 --password-stdin
            docker pull ghcr.io/kumsil1006/oao:oao-client
            docker pull ghcr.io/kumsil1006/oao:oao-proxy

            cd oao

            docker-compose up -d
            docker image prune

      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
