name: client build
on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - "client/**"

jobs:
  build-image:
    name: client image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install & Test
        run: |
          cd client
          yarn
          yarn build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kumsil1006
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ghcr.io/kumsil1006/oao:oao-client
          context: ./client

    - name: Copy Docker Compose into the Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ANOTHER_HOST }}
        username: ${{ secrets.ANOTHER_USERNAME }}
        password: ${{ secrets.ANOTHER_PASSWORD }}
        port: ${{ secrets.ANOTHER_PORT }}
        source: "docker-compose.yml"
        target: "oao"

      - name: Run Docker Compose on the Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ANOTHER_HOST }}
          username: ${{ secrets.ANOTHER_USERNAME }}
          password: ${{ secrets.ANOTHER_PASSWORD }}
          port: ${{ secrets.ANOTHER_PORT }}
          script: |
            echo ${{secrets.CONTAINER_REGISTRY_TOKEN}} | docker login ghcr.io -u kumsil1006 --password-stdin
            docker pull ghcr.io/kumsil1006/oao:oao-client
            docker pull ghcr.io/kumsil1006/oao:oao-proxy

            cd oao
            
            docker-compose up -d
            docker image prune
