name: server build
on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - "server/**"

jobs:
  build-image:
    name: server image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: compile Typescript files
        working-directory: "./server"
        env:
          CI: ""
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kumsil1006
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./server
          push: true
          tags: ghcr.io/kumsil1006/oao:oao-server

      - name: Run Docker Compose on the Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ANOTHER_HOST }}
          username: ${{ secrets.ANOTHER_USERNAME }}
          password: ${{ secrets.ANOTHER_PASSWORD }}
          port: ${{ secrets.ANOTHER_PORT }}
          envs: TOKEN
          script: |
            echo ${{secrets.CONTAINER_REGISTRY_TOKEN}} | docker login ghcr.io -u kumsil1006 --password-stdin
            docker pull ghcr.io/kumsil1006/oao:oao-server
            docker pull ghcr.io/kumsil1006/oao:oao-proxy
            docker-compose up -d
            docker image prune
