name: test
on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          
      - name: Install
        run: |
          cd client
          yarn

      - name: 테스트 코드 실행
        run: |
          cd client        
          yarn -s test

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: unittests # optional
